name: Deploy Python Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r MyFunctionProj/requirements.txt

      - name: Deploy to Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: myserverlessapi
          package: 'MyFunctionProj'


